{
  "uid" : "480cda3e71e1558",
  "name" : "Verifying the restoration mechanism -- @1.1 ",
  "fullName" : "Backup, Restore, and Update Mechanisms: Verifying the restoration mechanism",
  "historyId" : "e33ac408ddd3c43736640b06b9ead00b",
  "time" : {
    "start" : 1746705354884,
    "stop" : 1746705355456,
    "duration" : 572
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: STEP: When the admin uploads a backup file backup_20250128\n",
  "statusTrace" : "  File \"/home/runner/work/trustpoint/trustpoint/.venv/lib/python3.12/site-packages/behave/model.py\", line 1909, in run\n    match.run(runner.context)\n  File \"/home/runner/work/trustpoint/trustpoint/.venv/lib/python3.12/site-packages/behave/matchers.py\", line 104, in run\n    self.func(context, *args, **kwargs)\n  File \"trustpoint/features/steps/r_006_steps.py\", line 49, in step_when_admin_uploads_backup\n    raise AssertionError(msg)\n",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "failed",
    "statusMessage" : "AssertionError: STEP: When the admin uploads a backup file backup_20250128\n",
    "statusTrace" : "  File \"/home/runner/work/trustpoint/trustpoint/.venv/lib/python3.12/site-packages/behave/model.py\", line 1909, in run\n    match.run(runner.context)\n  File \"/home/runner/work/trustpoint/trustpoint/.venv/lib/python3.12/site-packages/behave/matchers.py\", line 104, in run\n    self.func(context, *args, **kwargs)\n  File \"trustpoint/features/steps/r_006_steps.py\", line 49, in step_when_admin_uploads_backup\n    raise AssertionError(msg)\n",
    "steps" : [ {
      "name" : "Given the admin user is logged into TPC_Web",
      "time" : {
        "start" : 1746705354886,
        "stop" : 1746705355428,
        "duration" : 542
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "When the admin uploads a backup file backup_20250128",
      "time" : {
        "start" : 1746705355428,
        "stop" : 1746705355428,
        "duration" : 0
      },
      "status" : "failed",
      "statusMessage" : "AssertionError: STEP: When the admin uploads a backup file backup_20250128\n",
      "statusTrace" : "  File \"/home/runner/work/trustpoint/trustpoint/.venv/lib/python3.12/site-packages/behave/model.py\", line 1909, in run\n    match.run(runner.context)\n  File \"/home/runner/work/trustpoint/trustpoint/.venv/lib/python3.12/site-packages/behave/matchers.py\", line 104, in run\n    self.func(context, *args, **kwargs)\n  File \"trustpoint/features/steps/r_006_steps.py\", line 49, in step_when_admin_uploads_backup\n    raise AssertionError(msg)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    }, {
      "name" : "Then the system restores the data successfully",
      "time" : {
        "start" : 1746705355456,
        "stop" : 1746705355456,
        "duration" : 0
      },
      "status" : "skipped",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "And the restored data is consistent with the backup file contents",
      "time" : {
        "start" : 1746705355456,
        "stop" : 1746705355456,
        "duration" : 0
      },
      "status" : "skipped",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 4,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "severity",
    "value" : "normal"
  }, {
    "name" : "feature",
    "value" : "Backup, Restore, and Update Mechanisms"
  }, {
    "name" : "framework",
    "value" : "behave"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "backup_file",
    "value" : "backup_20250128"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 2,
        "broken" : 0,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 2
      },
      "items" : [ {
        "uid" : "2894b1ce82f5756d",
        "reportUrl" : "https://Trustpoint-Project.github.io/trustpoint/16/#testresult/2894b1ce82f5756d",
        "status" : "failed",
        "statusDetails" : "AssertionError: STEP: When the admin uploads a backup file backup_20250128\n",
        "time" : {
          "start" : 1746616906074,
          "stop" : 1746616906652,
          "duration" : 578
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "480cda3e71e1558.json",
  "parameterValues" : [ "backup_20250128" ]
}