{
  "uid" : "fe64edf004834782",
  "name" : "Handling missing parameters during CA generation",
  "fullName" : "Auto-Generated Issuing CAs: Handling missing parameters during CA generation",
  "historyId" : "9ea1a96b61a133d568043e9ad268dd09",
  "time" : {
    "start" : 1746705362893,
    "stop" : 1746705363465,
    "duration" : 572
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: STEP: When the admin attempts to generate an Issuing CA with incomplete configuration\n",
  "statusTrace" : "  File \"/home/runner/work/trustpoint/trustpoint/.venv/lib/python3.12/site-packages/behave/model.py\", line 1909, in run\n    match.run(runner.context)\n  File \"/home/runner/work/trustpoint/trustpoint/.venv/lib/python3.12/site-packages/behave/matchers.py\", line 104, in run\n    self.func(context, *args, **kwargs)\n  File \"trustpoint/features/steps/r_008_steps.py\", line 71, in step_when_admin_attempts_incomplete_ca\n    raise AssertionError(msg)\n",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "failed",
    "statusMessage" : "AssertionError: STEP: When the admin attempts to generate an Issuing CA with incomplete configuration\n",
    "statusTrace" : "  File \"/home/runner/work/trustpoint/trustpoint/.venv/lib/python3.12/site-packages/behave/model.py\", line 1909, in run\n    match.run(runner.context)\n  File \"/home/runner/work/trustpoint/trustpoint/.venv/lib/python3.12/site-packages/behave/matchers.py\", line 104, in run\n    self.func(context, *args, **kwargs)\n  File \"trustpoint/features/steps/r_008_steps.py\", line 71, in step_when_admin_attempts_incomplete_ca\n    raise AssertionError(msg)\n",
    "steps" : [ {
      "name" : "Given the admin user is logged into TPC_Web",
      "time" : {
        "start" : 1746705362895,
        "stop" : 1746705363436,
        "duration" : 541
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "When the admin attempts to generate an Issuing CA with incomplete configuration",
      "time" : {
        "start" : 1746705363436,
        "stop" : 1746705363436,
        "duration" : 0
      },
      "status" : "failed",
      "statusMessage" : "AssertionError: STEP: When the admin attempts to generate an Issuing CA with incomplete configuration\n",
      "statusTrace" : "  File \"/home/runner/work/trustpoint/trustpoint/.venv/lib/python3.12/site-packages/behave/model.py\", line 1909, in run\n    match.run(runner.context)\n  File \"/home/runner/work/trustpoint/trustpoint/.venv/lib/python3.12/site-packages/behave/matchers.py\", line 104, in run\n    self.func(context, *args, **kwargs)\n  File \"trustpoint/features/steps/r_008_steps.py\", line 71, in step_when_admin_attempts_incomplete_ca\n    raise AssertionError(msg)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    }, {
      "name" : "Then the system prevents the CA from being generated",
      "time" : {
        "start" : 1746705363465,
        "stop" : 1746705363465,
        "duration" : 0
      },
      "status" : "skipped",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "And an appropriate error message is logged",
      "time" : {
        "start" : 1746705363465,
        "stop" : 1746705363465,
        "duration" : 0
      },
      "status" : "skipped",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 4,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "severity",
    "value" : "normal"
  }, {
    "name" : "feature",
    "value" : "Auto-Generated Issuing CAs"
  }, {
    "name" : "framework",
    "value" : "behave"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 2,
        "broken" : 0,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 2
      },
      "items" : [ {
        "uid" : "49703f5661617195",
        "reportUrl" : "https://Trustpoint-Project.github.io/trustpoint/16/#testresult/49703f5661617195",
        "status" : "failed",
        "statusDetails" : "AssertionError: STEP: When the admin attempts to generate an Issuing CA with incomplete configuration\n",
        "time" : {
          "start" : 1746616914210,
          "stop" : 1746616914789,
          "duration" : 579
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "fe64edf004834782.json",
  "parameterValues" : [ ]
}