{
  "uid" : "90c5266adf400971",
  "name" : "Successful auto-generation of an issuing CA",
  "fullName" : "Auto-Generated Issuing CAs: Successful auto-generation of an issuing CA",
  "historyId" : "37708dd66780ceb5d47b539d138c1065",
  "time" : {
    "start" : 1746710238627,
    "stop" : 1746710239195,
    "duration" : 568
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: STEP: When the admin configures the system for auto-generation of an Issuing CA\n",
  "statusTrace" : "  File \"/home/runner/work/trustpoint/trustpoint/.venv/lib/python3.12/site-packages/behave/model.py\", line 1909, in run\n    match.run(runner.context)\n  File \"/home/runner/work/trustpoint/trustpoint/.venv/lib/python3.12/site-packages/behave/matchers.py\", line 104, in run\n    self.func(context, *args, **kwargs)\n  File \"trustpoint/features/steps/r_008_steps.py\", line 14, in step_when_admin_configures_auto_ca\n    raise AssertionError(msg)\n",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "failed",
    "statusMessage" : "AssertionError: STEP: When the admin configures the system for auto-generation of an Issuing CA\n",
    "statusTrace" : "  File \"/home/runner/work/trustpoint/trustpoint/.venv/lib/python3.12/site-packages/behave/model.py\", line 1909, in run\n    match.run(runner.context)\n  File \"/home/runner/work/trustpoint/trustpoint/.venv/lib/python3.12/site-packages/behave/matchers.py\", line 104, in run\n    self.func(context, *args, **kwargs)\n  File \"trustpoint/features/steps/r_008_steps.py\", line 14, in step_when_admin_configures_auto_ca\n    raise AssertionError(msg)\n",
    "steps" : [ {
      "name" : "Given the admin user is logged into TPC_Web",
      "time" : {
        "start" : 1746710238629,
        "stop" : 1746710239167,
        "duration" : 538
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "When the admin configures the system for auto-generation of an Issuing CA",
      "time" : {
        "start" : 1746710239167,
        "stop" : 1746710239168,
        "duration" : 1
      },
      "status" : "failed",
      "statusMessage" : "AssertionError: STEP: When the admin configures the system for auto-generation of an Issuing CA\n",
      "statusTrace" : "  File \"/home/runner/work/trustpoint/trustpoint/.venv/lib/python3.12/site-packages/behave/model.py\", line 1909, in run\n    match.run(runner.context)\n  File \"/home/runner/work/trustpoint/trustpoint/.venv/lib/python3.12/site-packages/behave/matchers.py\", line 104, in run\n    self.func(context, *args, **kwargs)\n  File \"trustpoint/features/steps/r_008_steps.py\", line 14, in step_when_admin_configures_auto_ca\n    raise AssertionError(msg)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    }, {
      "name" : "Then the system automatically generates the CA",
      "time" : {
        "start" : 1746710239195,
        "stop" : 1746710239195,
        "duration" : 0
      },
      "status" : "skipped",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "And the generated CA appears in the list of available CAs",
      "time" : {
        "start" : 1746710239195,
        "stop" : 1746710239195,
        "duration" : 0
      },
      "status" : "skipped",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 4,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "severity",
    "value" : "normal"
  }, {
    "name" : "feature",
    "value" : "Auto-Generated Issuing CAs"
  }, {
    "name" : "framework",
    "value" : "behave"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 2,
        "broken" : 0,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 2
      },
      "items" : [ {
        "uid" : "6a93db483e08b16b",
        "reportUrl" : "https://Trustpoint-Project.github.io/trustpoint/20/#testresult/6a93db483e08b16b",
        "status" : "failed",
        "statusDetails" : "AssertionError: STEP: When the admin configures the system for auto-generation of an Issuing CA\n",
        "time" : {
          "start" : 1746709784756,
          "stop" : 1746709785325,
          "duration" : 569
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "90c5266adf400971.json",
  "parameterValues" : [ ]
}