{
  "uid" : "1f69bee36ac48578",
  "name" : "Verifying the backup mechanism -- @1.1 ",
  "fullName" : "Backup, Restore, and Update Mechanisms: Verifying the backup mechanism",
  "historyId" : "f8378de211ef0fdebac4909979724d24",
  "time" : {
    "start" : 1746708242749,
    "stop" : 1746708243327,
    "duration" : 578
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: STEP: When the admin initiates a system backup\n",
  "statusTrace" : "  File \"/home/runner/work/trustpoint/trustpoint/.venv/lib/python3.12/site-packages/behave/model.py\", line 1909, in run\n    match.run(runner.context)\n  File \"/home/runner/work/trustpoint/trustpoint/.venv/lib/python3.12/site-packages/behave/matchers.py\", line 104, in run\n    self.func(context, *args, **kwargs)\n  File \"trustpoint/features/steps/r_006_steps.py\", line 14, in step_when_admin_initiates_backup\n    raise AssertionError(msg)\n",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "failed",
    "statusMessage" : "AssertionError: STEP: When the admin initiates a system backup\n",
    "statusTrace" : "  File \"/home/runner/work/trustpoint/trustpoint/.venv/lib/python3.12/site-packages/behave/model.py\", line 1909, in run\n    match.run(runner.context)\n  File \"/home/runner/work/trustpoint/trustpoint/.venv/lib/python3.12/site-packages/behave/matchers.py\", line 104, in run\n    self.func(context, *args, **kwargs)\n  File \"trustpoint/features/steps/r_006_steps.py\", line 14, in step_when_admin_initiates_backup\n    raise AssertionError(msg)\n",
    "steps" : [ {
      "name" : "Given the admin user is logged into TPC_Web",
      "time" : {
        "start" : 1746708242751,
        "stop" : 1746708243298,
        "duration" : 547
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "When the admin initiates a system backup",
      "time" : {
        "start" : 1746708243298,
        "stop" : 1746708243298,
        "duration" : 0
      },
      "status" : "failed",
      "statusMessage" : "AssertionError: STEP: When the admin initiates a system backup\n",
      "statusTrace" : "  File \"/home/runner/work/trustpoint/trustpoint/.venv/lib/python3.12/site-packages/behave/model.py\", line 1909, in run\n    match.run(runner.context)\n  File \"/home/runner/work/trustpoint/trustpoint/.venv/lib/python3.12/site-packages/behave/matchers.py\", line 104, in run\n    self.func(context, *args, **kwargs)\n  File \"trustpoint/features/steps/r_006_steps.py\", line 14, in step_when_admin_initiates_backup\n    raise AssertionError(msg)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    }, {
      "name" : "Then the system confirms the backup process completes successfully",
      "time" : {
        "start" : 1746708243327,
        "stop" : 1746708243327,
        "duration" : 0
      },
      "status" : "skipped",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "And the backup file backup_20250128 is retrievable and valid",
      "time" : {
        "start" : 1746708243327,
        "stop" : 1746708243327,
        "duration" : 0
      },
      "status" : "skipped",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 4,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "severity",
    "value" : "normal"
  }, {
    "name" : "feature",
    "value" : "Backup, Restore, and Update Mechanisms"
  }, {
    "name" : "framework",
    "value" : "behave"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ {
    "name" : "backup_file",
    "value" : "backup_20250128"
  } ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 3,
        "broken" : 0,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 3
      },
      "items" : [ {
        "uid" : "a9218b4d1683542c",
        "reportUrl" : "https://Trustpoint-Project.github.io/trustpoint/17/#testresult/a9218b4d1683542c",
        "status" : "failed",
        "statusDetails" : "AssertionError: STEP: When the admin initiates a system backup\n",
        "time" : {
          "start" : 1746705354314,
          "stop" : 1746705354884,
          "duration" : 570
        }
      }, {
        "uid" : "3cbe8a4bc14cab18",
        "reportUrl" : "https://Trustpoint-Project.github.io/trustpoint/16/#testresult/3cbe8a4bc14cab18",
        "status" : "failed",
        "statusDetails" : "AssertionError: STEP: When the admin initiates a system backup\n",
        "time" : {
          "start" : 1746616905495,
          "stop" : 1746616906074,
          "duration" : 579
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "1f69bee36ac48578.json",
  "parameterValues" : [ "backup_20250128" ]
}